[project]
name = "homework-14-2"
version = "0.2.0"
description = "Интернет-магазин для курсовой работы"
authors = [
    {name = "Serg Medvedev",email = "medvserg@mail.ru"}
]
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ["py314"]

[tool.isort]
profile = "black"
line_length = 119

[tool.mypy]
python_version = "3.14"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
mypy_path = "src"
explicit_package_bases = true

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "isort (>=9.0.1,<10.0.0)",
    "mypy (>=2.3.1,<3.0.0)"
]
