[project]
name = "course-work-14-1"
version = "0.1.0"
description = "Интернет-магазин для курсовой работы"
authors = [
    {name = "Serg Medvedev",email = "medvserg@mail.ru"}
]
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "course_work_14"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "flake8 (>=7.3.0,<8.0.0)"
]
